include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    unawaited_futures: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    sort_pub_dependencies: false
